/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Citrus (https://sketchfab.com/citrusfriendd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/frog-cake-70154629c8bc432ba4e3aa68851ad8f4
Title: Frog Cake
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cake_lambert2_0.geometry} material={materials.lambert2} position={[0.2, 87.17, -0.17]} rotation={[0, -0.01, 0]} scale={[1.37, 0.87, 1.37]} />
      <mesh geometry={nodes.FrogBody_lambert3_0.geometry} material={materials.lambert3} position={[0, 205.23, 99.48]} rotation={[0.03, 0, 0]} scale={0.44} />
      <mesh geometry={nodes.Frosting_lambert2_0.geometry} material={materials.lambert2} position={[-102.98, 7.64, 95.05]} rotation={[0.09, -0.92, 3.02]} scale={[0.45, 0.31, 0.25]} />
      <mesh geometry={nodes.EyeLeft_lambert3_0.geometry} material={materials.lambert3} position={[22.04, 300.43, 101.94]} rotation={[0.03, 0, 0]} scale={0.69} />
      <mesh geometry={nodes.EyeRight_lambert3_0.geometry} material={materials.lambert3} position={[95.15, 300.43, 101.94]} rotation={[0.03, 0, 0]} scale={0.69} />
      <mesh geometry={nodes.Lilypad2_lambert2_0.geometry} material={materials.lambert2} position={[-48.15, 112.57, 0]} rotation={[0, 1.46, 0]} scale={[0.55, 0.6, 0.55]} />
      <mesh geometry={nodes.Lilypad_lambert2_0.geometry} material={materials.lambert2} position={[45.88, 119.68, -51.38]} rotation={[0, 0.65, 0]} scale={[0.49, 0.54, 0.49]} />
      <mesh geometry={nodes.SignBottom_lambert4_0.geometry} material={materials.lambert4} position={[-69.27, 190.98, -65.42]} rotation={[-0.05, 0.26, -0.02]} scale={[0.18, 0.48, 0.06]} />
      <mesh geometry={nodes.Signtop_lambert4_0.geometry} material={materials.lambert4} position={[-72.91, 230.9, -65.07]} rotation={[0, 0, 0.11]} scale={[0.99, 0.43, 0.13]} />
      <mesh geometry={nodes.LeafRight_lambert5_0.geometry} material={materials.lambert5} position={[-73.24, 18.29, -68.49]} rotation={[0, 0.95, 0]} scale={0.48} />
      <mesh geometry={nodes.LeafLeft_lambert5_0.geometry} material={materials.lambert5} position={[-52.65, 54.07, -68.49]} rotation={[-Math.PI, 0.68, -Math.PI]} scale={[0.4, 0.38, 0.48]} />
      <mesh geometry={nodes.Frosting1_lambert2_0.geometry} material={materials.lambert2} position={[-39.77, 0, -31.21]} rotation={[0, 0.27, 0]} />
      <mesh geometry={nodes.Frosting2_lambert2_0.geometry} material={materials.lambert2} position={[-59.39, 1.99, -3.7]} rotation={[0.02, 0.76, -0.02]} />
      <mesh geometry={nodes.Frosting3_lambert2_0.geometry} material={materials.lambert2} position={[-48.7, 2.3, 22.04]} rotation={[0.03, 1.15, -0.03]} />
      <mesh geometry={nodes.Frosting4_lambert2_0.geometry} material={materials.lambert2} position={[-35.6, 2.27, 35.37]} rotation={[0.3, 1.53, -0.29]} />
      <mesh geometry={nodes.Frosting5_lambert2_0.geometry} material={materials.lambert2} position={[-135.14, 3.42, 39.6]} rotation={[-0.3, -1.36, 2.56]} scale={[0.45, 0.31, 0.25]} />
      <mesh geometry={nodes.Frosting6_lambert2_0.geometry} material={materials.lambert2} position={[-9.07, -52.36, 22.94]} rotation={[-2.22, 1.24, 2.03]} />
      <mesh geometry={nodes.Frosting7_lambert2_0.geometry} material={materials.lambert2} position={[8.67, -30.04, 65.6]} rotation={[-3.05, 0.7, 2.75]} />
      <mesh geometry={nodes.Frosting8_lambert2_0.geometry} material={materials.lambert2} position={[23.72, 11.51, 53.86]} rotation={[3.07, 0.31, -3.1]} />
      <mesh geometry={nodes.Frosting9_lambert2_0.geometry} material={materials.lambert2} position={[43.92, 12.3, 32.46]} rotation={[3.09, -0.06, -3.1]} />
      <mesh geometry={nodes.Frosting10_lambert2_0.geometry} material={materials.lambert2} position={[76.52, 1.14, 14.63]} rotation={[3.11, -0.6, 3.04]} />
      <mesh geometry={nodes.Frosting11_lambert2_0.geometry} material={materials.lambert2} position={[58.64, 5.03, -3.51]} rotation={[3.07, -0.86, 3.01]} />
      <mesh geometry={nodes.Frosting12_lambert2_0.geometry} material={materials.lambert2} position={[43.56, 10.19, -26.7]} rotation={[2.92, -1.24, 2.88]} />
      <mesh geometry={nodes.Frosting13_lambert2_0.geometry} material={materials.lambert2} position={[32.28, 13.47, -42.37]} rotation={[0.55, -1.4, 0.53]} />
      <mesh geometry={nodes.Frosting14_lambert2_0.geometry} material={materials.lambert2} position={[-149.66, 3.42, -19.61]} rotation={[-2.09, -1.41, 0.78]} scale={[0.45, 0.31, 0.25]} />
      <mesh geometry={nodes.pCylinder1_lambert6_0.geometry} material={materials.lambert6} position={[32.01, 177.01, -83.78]} scale={[0.18, 0.12, 0.18]} />
      <mesh geometry={nodes.pCylinder2_lambert6_0.geometry} material={materials.lambert6} position={[-91.76, 177.01, -0.04]} scale={[0.2, 0.13, 0.2]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
